<Project>
    <PropertyGroup>
        <OctoRootDirectoryPropsFilePath>$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))</OctoRootDirectoryPropsFilePath>
        <OctoUserPropsFilePath>$([MSBuild]::GetPathOfFileAbove('Octo.User.props', '$(MSBuildThisFileDirectory)'))</OctoUserPropsFilePath>
        <OctoRepoRootPath>$(MSBuildThisFileDirectory)</OctoRepoRootPath>
        <OctoRepoRootPath Condition="'$(OctoRootDirectoryPropsFilePath)'!=''">$([System.IO.Path]::GetDirectoryName($(OctoRootDirectoryPropsFilePath)))</OctoRepoRootPath>
    </PropertyGroup>
    <!-- Import a custom file to overwrite versions etc. -->
    <Import Condition="'$(OctoRootDirectoryPropsFilePath)'=='' And Exists($(OctoUserPropsFilePath))" Project="$(OctoUserPropsFilePath)"/>
    <!-- Import the Directory.Build.props file of the root directory -->
    <Import Condition="Exists($(OctoRootDirectoryPropsFilePath))" Project="$(OctoRootDirectoryPropsFilePath)"/>
    <PropertyGroup>
        <LangVersion>latestmajor</LangVersion>
        <Nullable>enable</Nullable>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <ImplicitUsings>true</ImplicitUsings>
        <RepositoryUrl>https://github.com/meshmakers/one-time-ticket</RepositoryUrl>
        <PackageProjectUrl>https://www.meshmakers.io</PackageProjectUrl>
        <PackageTags>Octo data mesh iot</PackageTags>
        <TargetFramework>net10.0</TargetFramework>
        <OctoVersion Condition="'$(Configuration)'=='DebugL'">999.0.0</OctoVersion>
        <OctoVersion Condition="'$(OctoNugetPrivateServer)'!='' And '$(OctoVersion)'==''">0.1.*</OctoVersion>
        <OctoVersion Condition="'$(OctoNugetPrivateServer)'=='' And '$(OctoVersion)'==''">3.4.*</OctoVersion>
        <OctoCoreLibVersion Condition="'$(Configuration)'=='DebugL'">999.0.0</OctoCoreLibVersion>
        <OctoCoreLibVersion Condition="'$(OctoNugetPrivateServer)'!='' And '$(OctoCoreLibVersion)'==''">0.1.*</OctoCoreLibVersion>
        <OctoCoreLibVersion Condition="'$(OctoNugetPrivateServer)'=='' And '$(OctoCoreLibVersion)'==''">3.4.*</OctoCoreLibVersion>
        <Version Condition="'$(Configuration)'=='DebugL'">999.0.0</Version>
        <PackageVersion Condition="'$(Configuration)'=='DebugL'">999.0.0</PackageVersion>
        <RestoreSources Condition="'$(RestoreSources)'==''">https://api.nuget.org/v3/index.json</RestoreSources>
        <RestoreSources Condition="'$(OctoNugetPrivateServer)'!=''">$(OctoNugetPrivateServer)</RestoreSources>
        <RestoreSources Condition="'$(Configuration)'=='DebugL'">$(OctoRepoRootPath)../nuget;$(RestoreSources)</RestoreSources>
    </PropertyGroup>
</Project>
